apiVersion: v1
kind: Namespace
metadata:
  name: akkluster

---

apiVersion: v1
kind: Service
metadata:
  namespace: akkluster
  name: akkluster-http
spec:
  selector:
    app: akkluster
    kind: static
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http

---

apiVersion: v1
kind: Service
metadata:
  namespace: akkluster
  name: akkluster-management
spec:
  selector:
    app: akkluster
  type: NodePort
  ports:
  - name: management
    port: 8558
    targetPort: management

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: akkluster
  name: akkluster-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akkluster
      kind: static
  template:
    metadata:
      namespace: akkluster
      name: akkluster
      labels:
        app: akkluster
        kind: static
    spec:
      containers:
      - name: akkluster
        image: hseeberger/akkluster:latest
        imagePullPolicy: IfNotPresent
        args: [
            "-Dakka.cluster.roles.0=static"
          #              "-Dakka.cluster.downing-provider-class=rocks.heikoseeberger.akkluster.NaiveDowningProvider"
          #              "-Dakka.cluster.downing-provider-class=com.lightbend.akka.sbr.SplitBrainResolverProvider",
          #              "-Dakka.cluster.split-brain-resolver.active-strategy=keep-majority",
          #              "-Dakka.cluster.split-brain-resolver.stable-after=7seconds"
        ]
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 8558
        - name: akka-remote
          containerPort: 25520
        securityContext:
          capabilities:
            add:
            - NET_ADMIN

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: akkluster
  name: akkluster-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akkluster
      kind: dynamic
  template:
    metadata:
      namespace: akkluster
      name: akkluster
      labels:
        app: akkluster
        kind: dynamic
    spec:
      containers:
      - name: akkluster
        image: hseeberger/akkluster:latest
        imagePullPolicy: IfNotPresent
        args: [
            "-Dakka.cluster.roles.0=dynamic"
          #              "-Dakka.cluster.downing-provider-class=rocks.heikoseeberger.akkluster.NaiveDowningProvider"
          #              "-Dakka.cluster.downing-provider-class=com.lightbend.akka.sbr.SplitBrainResolverProvider",
          #              "-Dakka.cluster.split-brain-resolver.active-strategy=keep-majority",
          #              "-Dakka.cluster.split-brain-resolver.stable-after=7seconds"
        ]
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: 8558
        - name: akka-remote
          containerPort: 25520
        securityContext:
          capabilities:
            add:
            - NET_ADMIN

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: akkluster
  name: pod-reader
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "watch", "list" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: akkluster
  name: read-pods
subjects:
- kind: User
  name: system:serviceaccount:akkluster:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
