#!/bin/sh

usage() {
  echo "Deploy to k8s"
  echo "  -h  Print usage instructions"
  echo "  -v  Version of the Docker image, i.e. the value of the tag"
}

while getopts ":hv:" opt; do
  case ${opt} in
  h)
    usage
    exit 0
    ;;
  v)
    version=${OPTARG}
    ;;
  \?)
    echo "Invalid option: -${opt}" >&2
    usage
    exit 1
    ;;
  :)
    echo "Option -${opt} requires an argument" >&2
    usage
    exit 1
    ;;
  esac
done
shift $(($OPTIND - 1))

if [ -z "${version}" ]; then
  version=$(docker images --format "{{.Tag}}" hseeberger/akkluster | sort -r | head -1)
elif [ -z $(docker images --format "{{.Tag}}" hseeberger/akkluster | grep -x ${version}) ]; then
  echo "Unknown version: ${version}" >&2
  exit 1
fi

dir=$(pwd)
cd $(dirname $0)

cp kustomization.yaml /tmp/
kustomize edit set image hseeberger/akkluster:${version}
kubectl apply -k .

cp /tmp/kustomization.yaml .
cd $dir
