addSbtPlugin("com.dwijnand"            % "sbt-dynver"          % "4.0.0")
addSbtPlugin("com.typesafe.sbt"        % "sbt-native-packager" % "1.7.0")
addSbtPlugin("de.heikoseeberger"       % "sbt-header"          % "5.4.0")
addSbtPlugin("org.scalameta"           % "sbt-scalafmt"        % "2.3.2")
addSbtPlugin("io.spray"                % "sbt-revolver"        % "0.9.1")
