addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "4.1.1")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.6")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.9.1")
